// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcppeigen_quadratic_solve
Eigen::VectorXd rcppeigen_quadratic_solve(Eigen::MatrixXd& G, Eigen::VectorXd& g0, const Eigen::MatrixXd& CE, const Eigen::VectorXd& ce0, const Eigen::MatrixXd& CI, const Eigen::VectorXd& ci0);
RcppExport SEXP quadprogpp_quadratic_solve(SEXP GSEXP, SEXP g0SEXP, SEXP CESEXP, SEXP ce0SEXP, SEXP CISEXP, SEXP ci0SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type G(GSEXP );
        Rcpp::traits::input_parameter< Eigen::VectorXd& >::type g0(g0SEXP );
        Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type CE(CESEXP );
        Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ce0(ce0SEXP );
        Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type CI(CISEXP );
        Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ci0(ci0SEXP );
        Eigen::VectorXd __result = rcppeigen_quadratic_solve(G, g0, CE, ce0, CI, ci0);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
